BEGIN TRANSACTION; 

DROP TABLE PRECONISATION;
DROP TABLE HISTORIQUE_COMMENTAIRE;
DROP TABLE COMMENTAIRE;
DROP TABLE NOTE;
DROP TABLE BLOC;
DROP TABLE RUBRIQUE_ARTICLE;
DROP TABLE RUBRIQUE;
DROP TABLE TAGS;
DROP TABLE TIE_ARTICLE;
DROP TABLE HISTORIQUE_ARTICLE;
DROP TABLE ARTICLE;
DROP TABLE DROIT_USER;
DROP TABLE TUSER;

DROP SEQUENCE idauto_art;
DROP SEQUENCE idauto_comm;
COMMIT;
